#include "completion.h"

#include <stdio.h>

void completion_bash(void) {
    printf("_mux() {\n"
           "    local cur prev commands projects\n"
           "    COMPREPLY=()\n"
           "    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
           "    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n"
           "    commands=\"start stop new copy delete list debug local doctor implode "
           "stop-all version help completions\"\n"
           "\n"
           "    if [ $COMP_CWORD -eq 1 ]; then\n"
           "        COMPREPLY=( $(compgen -W \"$commands\" -- \"$cur\") )\n"
           "        return 0\n"
           "    fi\n"
           "\n"
           "    case \"$prev\" in\n"
           "        start|stop|debug|delete|copy)\n"
           "            projects=$(mux list 2>/dev/null)\n"
           "            COMPREPLY=( $(compgen -W \"$projects\" -- \"$cur\") )\n"
           "            return 0\n"
           "            ;;\n"
           "        completions)\n"
           "            COMPREPLY=( $(compgen -W \"bash zsh fish\" -- \"$cur\") )\n"
           "            return 0\n"
           "            ;;\n"
           "    esac\n"
           "}\n"
           "complete -F _mux mux\n");
}

void completion_zsh(void) {
    printf("#compdef mux\n"
           "\n"
           "_mux() {\n"
           "    local -a commands\n"
           "    commands=(\n"
           "        'start:Start a tmux session'\n"
           "        'stop:Stop a tmux session'\n"
           "        'new:Create a new project config'\n"
           "        'copy:Copy a project config'\n"
           "        'delete:Delete project configs'\n"
           "        'list:List available projects'\n"
           "        'debug:Print generated tmux script'\n"
           "        'local:Start from local .tmuxinator.yml'\n"
           "        'doctor:Check dependencies'\n"
           "        'implode:Delete all configs'\n"
           "        'stop-all:Stop all tmux sessions'\n"
           "        'version:Print version'\n"
           "        'help:Show help'\n"
           "        'completions:Print shell completion script'\n"
           "    )\n"
           "\n"
           "    if (( CURRENT == 2 )); then\n"
           "        _describe -t commands 'mux commands' commands\n"
           "    elif (( CURRENT == 3 )); then\n"
           "        case $words[2] in\n"
           "            start|stop|debug|delete|copy)\n"
           "                local -a projects\n"
           "                projects=(${(f)\"$(mux list 2>/dev/null)\"})\n"
           "                _describe -t projects 'projects' projects\n"
           "                ;;\n"
           "            completions)\n"
           "                local -a shells\n"
           "                shells=(bash zsh fish)\n"
           "                _describe -t shells 'shells' shells\n"
           "                ;;\n"
           "        esac\n"
           "    fi\n"
           "}\n"
           "\n"
           "_mux\n");
}

void completion_fish(void) {
    printf("# Fish completions for mux\n"
           "complete -c mux -f\n"
           "\n"
           "# Commands\n"
           "complete -c mux -n '__fish_use_subcommand' -a start -d 'Start a tmux session'\n"
           "complete -c mux -n '__fish_use_subcommand' -a stop -d 'Stop a tmux session'\n"
           "complete -c mux -n '__fish_use_subcommand' -a new -d 'Create a new project config'\n"
           "complete -c mux -n '__fish_use_subcommand' -a copy -d 'Copy a project config'\n"
           "complete -c mux -n '__fish_use_subcommand' -a delete -d 'Delete project configs'\n"
           "complete -c mux -n '__fish_use_subcommand' -a list -d 'List available projects'\n"
           "complete -c mux -n '__fish_use_subcommand' -a debug -d 'Print generated tmux "
           "script'\n"
           "complete -c mux -n '__fish_use_subcommand' -a local -d 'Start from local config'\n"
           "complete -c mux -n '__fish_use_subcommand' -a doctor -d 'Check dependencies'\n"
           "complete -c mux -n '__fish_use_subcommand' -a implode -d 'Delete all configs'\n"
           "complete -c mux -n '__fish_use_subcommand' -a stop-all -d 'Stop all sessions'\n"
           "complete -c mux -n '__fish_use_subcommand' -a version -d 'Print version'\n"
           "complete -c mux -n '__fish_use_subcommand' -a help -d 'Show help'\n"
           "complete -c mux -n '__fish_use_subcommand' -a completions -d 'Print completion "
           "script'\n"
           "\n"
           "# Project name completions\n"
           "complete -c mux -n '__fish_seen_subcommand_from start stop debug delete copy' "
           "-a '(mux list 2>/dev/null)'\n"
           "\n"
           "# Shell completions\n"
           "complete -c mux -n '__fish_seen_subcommand_from completions' -a 'bash zsh fish'\n");
}
